substitutions:
  name: itho-ventilation
  friendly_name: Itho Ventilation

packages:
  base: !include common/base.yaml

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino

logger:
  level: WARN
  baud_rate: 0

modbus:
  flow_control_pin: 5
  id: modbus1
  uart_id: mod_uart

uart:
  id: mod_uart
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 19200
  parity: EVEN
  stop_bits: 1
  data_bits: 8

modbus_controller:
  - id: itho_ventilation
    address: 72 ## the Modbus device addr
    modbus_id: modbus1
    update_interval: 20s
    setup_priority: -10
    command_throttle: 200ms

sensor:
  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "highest % supply automode"
    id: hru_supply_maxperc
    register_type: holding
    address: 3000
    value_type: U_WORD
    unit_of_measurement: "%"

  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "highest % exhaust automode"
    id: hru_exhaust_maxperc
    register_type: holding
    address: 3001
    value_type: U_WORD
    unit_of_measurement: "%"

  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "highest % RV non-fan"
    id: hru_RV_ext_maxperc
    register_type: holding
    address: 3010
    value_type: U_WORD
    unit_of_measurement: "%"

  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "highest ppm CO2 non-fan"
    id: hru_co2_maxperc
    register_type: holding
    address: 3011
    value_type: U_WORD
    unit_of_measurement: "ppm"

  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "snelheid supplyventilator"
    id: hru_rpm_supplyventilator
    register_type: holding
    address: 3020
    value_type: U_WORD
    unit_of_measurement: "rpm"

  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "snelheid exhaustventilator"
    id: hru_rpm_exhaustventilator
    register_type: holding
    address: 3021
    value_type: U_WORD
    unit_of_measurement: "rpm"

  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "power supplyventilator"
    id: hru_pwr_supplyventilator
    register_type: holding
    address: 3022
    value_type: U_WORD
    unit_of_measurement: "W"

  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "power exhaustventilator"
    id: hru_pwr_exhaustventilator
    register_type: holding
    address: 3023
    value_type: U_WORD
    unit_of_measurement: "W"

  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "m3/h supply van buiten"
    id: hru_m3h_supply_external
    register_type: holding
    address: 3030
    value_type: U_WORD
    unit_of_measurement: "m3/h"

  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "Massastroom van buitenaf"
    id: hru_massastroom_buiten
    register_type: holding
    address: 3031
    value_type: U_WORD
    unit_of_measurement: "kg/h"

  - platform: modbus_controller # 0x91 type, signed 16bit/10
    modbus_controller_id: itho_ventilation
    name: "temp supply van buiten"
    id: hru_temp_supply_external
    register_type: holding
    address: 3032
    value_type: S_WORD
    filters:
      - multiply: 0.10
    unit_of_measurement: "°C"

  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "humidity supply van buiten"
    id: hru_hum_supply_external
    register_type: holding
    address: 3033
    value_type: U_WORD
    unit_of_measurement: "%"

  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "m3/h supply gemengd"
    id: hru_m3h_supply_gemengd
    register_type: holding
    address: 3050
    value_type: U_WORD
    unit_of_measurement: "m3/h"

  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "massastroom gemengd"
    id: hru_massastroom_gemengd
    register_type: holding
    address: 3051
    value_type: U_WORD
    unit_of_measurement: "kg/h"

  - platform: modbus_controller # 0x91 type, signed 16bit/10
    modbus_controller_id: itho_ventilation
    name: "temp supply gemengd"
    id: hru_temp_supply_gemengd
    register_type: holding
    address: 3052
    value_type: S_WORD
    filters:
      - multiply: 0.10
    unit_of_measurement: "°C"

  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "humidity supply gemengd"
    id: hru_hum_supply_gemengd
    register_type: holding
    address: 3053
    value_type: U_WORD
    unit_of_measurement: "%"

  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "m3/h supply binnen totaal"
    id: hru_m3h_supply_binnen_total
    register_type: holding
    address: 3060
    value_type: U_WORD
    unit_of_measurement: "m3/h"

  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "massastroom naar gebouw"
    id: hru_massastroom_gebouw
    register_type: holding
    address: 3061
    value_type: U_WORD
    unit_of_measurement: "kg/h"

  - platform: modbus_controller # 0x91 type, signed 16bit/10
    modbus_controller_id: itho_ventilation
    name: "temp supply binnen"
    id: hru_temp_supply_binnen
    register_type: holding
    address: 3062
    value_type: S_WORD
    filters:
      - multiply: 0.10
    unit_of_measurement: "°C"

  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "humidity supply naar gebouw"
    id: hru_hum_supply_binnen
    register_type: holding
    address: 3063
    value_type: U_WORD
    unit_of_measurement: "%"

  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "m3/h exhaust totaal"
    id: hru_m3h_exhaust_binnen
    register_type: holding
    address: 3070
    value_type: U_WORD
    unit_of_measurement: "m3/h"

  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "massastroom van gebouw"
    id: hru_massastroom_van_gebouw
    register_type: holding
    address: 3071
    value_type: U_WORD
    unit_of_measurement: "kg/h"

  - platform: modbus_controller # 0x91 type, signed 16bit/10
    modbus_controller_id: itho_ventilation
    name: "temp exhaust binnen"
    id: hru_temp_exhaust_binnen
    register_type: holding
    address: 3072
    value_type: S_WORD
    filters:
      - multiply: 0.10
    unit_of_measurement: "°C"

  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "humidity exhaust binnen"
    id: hru_hum_exhaust_binnen
    register_type: holding
    address: 3073
    value_type: U_WORD
    unit_of_measurement: "%"
    filters:
      - or:
          - delta: 1
          - heartbeat: 60s
      - lambda: float rand1 = rand() % 1;
          return x + rand1;

  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "m3/h exhaust buiten"
    id: hru_m3h_exhaust_buiten
    register_type: holding
    address: 3080
    value_type: U_WORD
    unit_of_measurement: "m3/h"

  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "massastroom naar buiten"
    id: hru_massastroom_naar_buiten
    register_type: holding
    address: 3081
    value_type: U_WORD
    unit_of_measurement: "kg/h"

  - platform: modbus_controller # 0x91 type, signed 16bit/10
    modbus_controller_id: itho_ventilation
    name: "temp exhaust buiten"
    id: hru_temp_exhaust_buiten
    register_type: holding
    address: 3082
    value_type: S_WORD
    filters:
      - multiply: 0.10
    unit_of_measurement: "°C"

  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "humidity exhaust buiten"
    id: hru_hum_exhaust_buiten
    register_type: holding
    address: 3083
    value_type: U_WORD
    unit_of_measurement: "%"

number:
  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "m3/h vraag supply"
    address: 2010
    value_type: U_WORD
    min_value: 0
    max_value: 399
    step: 1
    id: hru_zone2stroomvraag
    register_type: holding
    use_write_multiple: true
  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "ventilation level"
    address: 2000
    value_type: U_WORD
    min_value: 1
    max_value: 25
    step: 1
    id: hru_ventilationlevel
    register_type: holding
    use_write_multiple: true

switch:
  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "m3/h vraag supply on/off"
    address: 2011
    id: hru_zone2stroomvraag_on
    register_type: holding
    use_write_multiple: true
  - platform: modbus_controller
    modbus_controller_id: itho_ventilation
    name: "ventilation level on/off"
    address: 2001
    id: hru_ventilationlevel_on
    register_type: holding
    use_write_multiple: true
