substitutions:
  device_name: "nspanel-kitchen"
  friendly_name: "NSPanel Kitchen"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  #nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional

api:
  encryption:
    key: !secret api_key
wifi:
  networks:
    - id: !extend wifi_default
      hidden: true
  fast_connect: true

# Core and optional configurations
packages:
  remote_package:
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint
    ref: main
    refresh: 300s
    files:
      - nspanel_esphome.yaml
      - esphome/nspanel_esphome_addon_bluetooth_proxy.yaml